# Generated by Django 4.2.16 on 2024-11-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hos', 'House'), ('apt', 'Apartment'), ('cdm', 'Condominium'), ('cml', 'Commercial')], max_length=3)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
