# Generated by Django 4.2.16 on 2024-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketlistings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
