# Generated by Django 4.2.16 on 2024-11-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketlistings', '0002_remove_listing_coordinates_listing_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='floor_area',
            new_name='building_size',
        ),
    ]
